package debug

import (
	"io"
	"net/http"

	"backend-go/internal/infra/pdf"
	"backend-go/pkg/config"

	"github.com/gin-gonic/gin"
)

// RegisterRoutes registers the debug routes.
func RegisterRoutes(rg *gin.RouterGroup) {
	pdfProvider := pdf.NewRemotePdfProvider(config.AppConfig.PdfServiceUrl)
	h := &DebugHandler{pdfProvider: pdfProvider}

	debugRoutes := rg.Group("/debug/pdf")
	{
		debugRoutes.POST("", h.TestPdf)
		debugRoutes.GET("", h.TestPdfGet)
	}
}

// DebugHandler handles debug requests.
type DebugHandler struct {
	pdfProvider pdf.PdfProvider
}

// TestPdf handles POST /v1/debug/pdf
func (h *DebugHandler) TestPdf(c *gin.Context) {
	var request pdf.PdfRequestDTO
	if err := c.ShouldBindJSON(&request); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	pdfStream, err := h.pdfProvider.GeneratePdf(request)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	defer pdfStream.Close()

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", "attachment; filename=\"test.pdf\"")
	
	// Stream the response directly to the client
	if _, err := io.Copy(c.Writer, pdfStream); err != nil {
		// Log error but we already started sending response
		return
	}
}

// TestPdfGet handles GET /v1/debug/pdf
func (h *DebugHandler) TestPdfGet(c *gin.Context) {
	request := pdf.PdfRequestDTO{
		Template: "simple",
		Data: map[string]interface{}{
			"title":   "PDF Streaming Bypass Test",
			"content": "Generated by backend-go using react-pdf-service",
		},
	}

	pdfStream, err := h.pdfProvider.GeneratePdf(request)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	defer pdfStream.Close()

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", "inline; filename=\"test.pdf\"")

	// Stream the response directly to the client
	if _, err := io.Copy(c.Writer, pdfStream); err != nil {
		return
	}
}
