package debug

import (
	"io"
	"net/http"

	"backend-go/internal/infra/pdf"
	"backend-go/pkg/config"

	"github.com/gin-gonic/gin"
)

// RegisterRoutes registers the debug routes.
func RegisterRoutes(rg *gin.RouterGroup) {
	pdfProvider := pdf.NewRemotePdfProvider(config.AppConfig.PdfServiceUrl)
	h := &DebugHandler{pdfProvider: pdfProvider}

	debugRoutes := rg.Group("/debug/pdf")
	{
		debugRoutes.POST("", h.TestPdf)
		debugRoutes.GET("", h.TestPdfGet)
	}
}

// DebugHandler handles debug requests.
type DebugHandler struct {
	pdfProvider pdf.PdfProvider
}

// TestPdf handles POST /v1/debug/pdf
func (h *DebugHandler) TestPdf(c *gin.Context) {
	var request pdf.PdfRequestDTO
	if err := c.ShouldBindJSON(&request); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	pdfStream, err := h.pdfProvider.GeneratePdf(request)
	if err != nil {
		mockPdfBytes := []byte("%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> >>\nendobj\nxref\n0 4\n0000000000 65535 f\n0000000009 00000 n\n0000000058 00000 n\n0000000115 00000 n\ntrailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n190\n%%EOF")
		c.Header("Content-Type", "application/pdf")
		c.Header("Content-Disposition", "attachment; filename=\"test.pdf\"")
		c.Writer.Write(mockPdfBytes)
		return
	}
	defer pdfStream.Close()

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", "attachment; filename=\"test.pdf\"")
	
	// Stream the response directly to the client
	if _, err := io.Copy(c.Writer, pdfStream); err != nil {
		// Log error but we already started sending response
		return
	}
}

// TestPdfGet handles GET /v1/debug/pdf
func (h *DebugHandler) TestPdfGet(c *gin.Context) {
	request := pdf.PdfRequestDTO{
		Template: "simple",
		Data: map[string]interface{}{
			"title":   "PDF Streaming Bypass Test",
			"content": "Generated by backend-go using react-pdf-service",
		},
	}

	pdfStream, err := h.pdfProvider.GeneratePdf(request)
	if err != nil {
		mockPdfBytes := []byte("%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> >>\nendobj\nxref\n0 4\n0000000000 65535 f\n0000000009 00000 n\n0000000058 00000 n\n0000000115 00000 n\ntrailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n190\n%%EOF")
		c.Header("Content-Type", "application/pdf")
		c.Header("Content-Disposition", "inline; filename=\"test.pdf\"")
		c.Writer.Write(mockPdfBytes)
		return
	}
	defer pdfStream.Close()

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", "inline; filename=\"test.pdf\"")

	// Stream the response directly to the client
	if _, err := io.Copy(c.Writer, pdfStream); err != nil {
		return
	}
}
